### ISSUE TITLE
JS Error

### ISSUE THREAD

**Issue by karumank** [rajatsehgal/add-to-home-screen#1]
I get the below error when I try to import your module

Failed to compile.

./node_modules/@rajatsehgal/add-to-home-screen/AddToHomeScreen.js
Module parse failed: Unexpected token (16:14)
You may need an appropriate loader to handle this file type.
|   }
| 
|   handleClose = () => {
|     this.setState({
|       visible: false

**Comment by m0veax** [comment]
Same for me

**Comment by rajatsehgal** [comment]
Converted to a web component instead, with no other dependencies.
